### ISSUE TITLE
Updating Description on Github doesn't result in updated view on website

### ISSUE THREAD

**Issue by AABoyles** [CDCgov/cdcgov.github.io#3]
Looks like the API pull isn't overwriting the cached results properly. 

Maybe we should abandon the cache altogether. and just hammer the API with pagination?

**Comment by AABoyles** [comment]
Looks like API results are sorted by `created`, but we need to check `updated` to match the default sort order of the app. See https://developer.github.com/v3/repos/#list-organization-repositories

**Comment by leebrian** [comment]
Or would it be worth just building projects.json at commit time and then statically generate the site once hitting the api only at build? This would reduce us from hitting the api for each visitor. We would lose updates between commits, but I don't think descriptions change very frequently.

I don't know how to generate static content for GitHub though as I've only done it on GitLab.

**Comment by AABoyles** [comment]
We could write a little node script. Heck, 90% of it is already written in [index,html](https://github.com/CDCgov/cdcgov.github.io/blob/master/index.html#L207)

Unfortunately, we'd lose a little more than just up-to-date descriptions. By dropping the client API call, we lose the up-to-date sequencing of the last updated repositories (the current last updated should be *this* one, but isn't, caused by this very bug!), and any other metadata that's changed in the intervening time. Not saying we can't do it, but it's a non-trivial tradeoff.
