### ISSUE TITLE
Project linter/formatter preference?

### ISSUE THREAD

**Issue by leebrian** [CDCgov/cdcgov.github.io#9]
I'm embarassed because my pull request included a default reformat that I forgot to undo before commit. What preference do you have for lint/autoformat so I can adopt them? I don't care, but don't want to waste your time and make merges harder than they should be?

**Comment by AABoyles** [comment]
Don't sweat it! I use [Atom's](https://atom.io/) autoindenting, but don't typically run code through a more rigorous process. What did you use to reformat the code? I could submit a PR to change it back, or just continue dev on it as is (which is my inclination).

**Comment by leebrian** [comment]
I noticed it because it was hard for me to see the actual line I changed :) So I annoyed myself. My formatting was unintentional as I didn't know my vscode had beautify installed because it wasn't my normal rig and was in a meeting.

Beautify works across atom and code, but so does Prettier. If you want to pick one, I'll use it. Or I can just chalk this up to a "my problem" and stick with vi.

Since you actually did this, my goal is to not cause chaos for you. I think the default editorconfig, https://editorconfig.org/, matches atom's default and I'll use that to make any future contribs from me easier.

**Comment by AABoyles** [comment]
Oh neat--I'd never heard of editorconfig before, but that's such a good and clever idea! I've added (cfbe329d841e284f0a923632687d6631826c8aca) [an editorconfig file](https://github.com/CDCgov/cdcgov.github.io/blob/master/.editorconfig) which suits my style well enough, so we should be good to go!
